<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# 1 Lists, Arrays, Dictionaries & tuple

## 1.1 Let’s compare

In [45]:
py_list = ["black widow","iron man","Doctor Strange"] #python list exists as a class in default python package
pylist_2d = [py_list,"1",10,["apple","banana"]]#also able to store multiple classes, including other lists


In [46]:
import numpy as np
np_array = np.array(["black widow","iron man","doctor strange"])
np_similar = np.array(py_list)  #numpy array, accepts lists
np_similar.dtype               #however, the contents of list can only be of single class


dtype('<U14')

In [1]:
dict1 = {"natasha romanoff": "black widow","tony stark": "iron man","stephen strange": "doctor strange"} #dictionary class, assigns value to a key 

In [6]:
 list(dict1)

['natasha romanoff', 'tony stark', 'stephen strange']

In [57]:
tuple1 = ("black widow", "iron man", "doctor strange") #tuple are immutable while lists are mutable

## 1.2 Accessing data from a list (or array)

In [13]:
print(py_list[0]) #index starts from 0 in python
print(py_list[-1]) #negative number to start from end, useful for when length is unknown
#print(py_list[3]) #using index out of range throws error
print(np_array[1]) #np_array can be referenced similar to list

black widow
Doctor Strange
iron man


## 1.3 Accessing data from a dictionary

In [15]:
dict1.keys()
dict1.values()

dict_values(['black widow', 'iron man', 'doctor strange'])

In [17]:
dict1["natasha romanoff"] #keys can be used to reference values
#dict1["black widow"] #but vice versa does not work

KeyError: 'black widow'

## 1.4 Higher dimensional lists

In [23]:
pylist_2 = [['Natasha Romanoff', 'Black Widow'],['Tony Stark', 'Iron Man'],['Stephen Strange', 'Doctor Strange']] #A 2D list

# 2 Lists vs. Arrays

## 2.1 Size

In [25]:
len(py_list) 
len(np_array) #len function works for both list and array
np_array_2d = np.array(pylist_2)
np_array_2d.shape #length,dimension

(3, 2)

## 2.2 Arrays are fussy about type

In [47]:
pylist_22 = [["a",3],["b",1],["c",2]]
print(np.array(pylist_22))  #note that array only allows 1 class, seems to convert int to str with no issue
pylist_test = [[0,False],[1,True],[2,True]]
print(np.array(pylist_test)) #in this case, boolean converts to int

#data type can be checked with the param array.dtype

[['a' '3']
 ['b' '1']
 ['c' '2']]
[[0 0]
 [1 1]
 [2 1]]


## 2.3 Adding a number

In [17]:
py_list1 = [1,2,3,4,5]
np_array1 = np.array(py_list1)
#py_list + 10 #throws error, only concat/append allowed
print(py_list1 + [10]) #concat list of single value 10 to end
print([x + 10 for x in py_list1]) #to add 10 to each element within
py_list1.append(10) #append method of list
print(py_list1)
print(np_array1 + 10) #for array, 10 is added to each value within
np.append(np_array1 , 10) #to append an numpy array

[1, 2, 3, 4, 5, 10]
[11, 12, 13, 14, 15]
[1, 2, 3, 4, 5, 10]
[11 12 13 14 15]


array([ 1,  2,  3,  4,  5, 10])

## 2.4 Adding another list

In [3]:
import numpy as np
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [ ]:
py_list_1 + py_list_2 #the two list concats, with the second list in the equation being appended behind the first

In [4]:
np_array_1 + np_array_2 #the values of the elements are added together in array

array([11, 22, 33, 44, 55])

In [10]:
np_array_short = np.array([1,2])
np_array_long = np.array([1,2,3,4])
#np_array_short + np_array_long #array of different length cannot be added directly
np_array_long[:len(np_array_short)] += np_array_short #note longer array is needed for "template", so length comparison might be needed if array lengths are unknown
np_array_long

array([2, 4, 3, 4])

## 2.5 Multiplying by a Number

In [4]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         


In [6]:
py_list*2 #doubles list by appending list elements
[x*2 for x in py_list] #in order to multiple all element by 2

[2, 4, 6, 8, 10]

In [19]:
np_array*2 

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [9]:
#py_list**2   #I wish this made it a 2d array, but alas it throws error
[x**2 for x in py_list] #in order to square all elements in list

[1, 4, 9, 16, 25]

In [21]:
np_array**2

array([ 1,  4,  9, 16, 25])

## 2.7 Asking questions

In [ ]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [11]:
print(py_list == 3 )    # asks if py_list is equal to 3 ie [1,2,3,4,5] == 3
print(py_list == [1,2,3,4,5]) #refer to fundamentals_(nice) for more detail

False
True


In [26]:
py_list > 3 #no logical operation here

TypeError: '>' not supported between instances of 'list' and 'int'

In [12]:
np_array == 3  #checks each element for equality to 3, returns boolean mask array

array([False, False,  True, False, False])

In [52]:
np_array > 3  #checks each element if they are larger than 3
sum(np_array <2) #returns sum of true from array that is returned from the logical operation

1

## 2.8 Mathematics

In [49]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array([5,3,4,1,2])         

In [29]:
sum(py_list)     # sum() is a base Python function

15

In [ ]:
max(py_list)     # max() is a base Python function

In [ ]:
min(py_list)     # min() is a base Python function

In [30]:
py_list.sum() #list class does not have sum method

AttributeError: 'list' object has no attribute 'sum'

In [38]:
np_array.sum() #but array does
sum(np_array) #of course, sum function also applies to arrays

15

In [36]:
np_array.max()
max(np_array)

5

In [39]:
np_array.min()
min(np_array)

1

In [51]:
np_array.mean()
np_array.std() #array also have more stat methods
np_array.sort() #also works for multidimensional arrays, of which axis has to be specified
print(np_array)

[1 2 3 4 5]


## Footnotes