<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

let our sample list be `pylist = ["a1", "b2", "c3", "d4", "e5","f6", "g7", "h8", "i9", "j10"]`

The following will work for both lists and arrays

| Syntax    | Result                          | Output                          | Note                                    |
|-----------|---------------------------------|---------------------------------|-----------------------------------------|
| x[0]      | First element                   | 'a1'                            |                                         |
| x[-1]     | Last element                    | 'j10'                           |                                         |
| x[0:3]    | Index 0 to 2                    | ['a1','b2','c3']                | Gives 3 - 0 = 3 elements                |
| x[1:6]    | Index 1 to 5                    | ['b2','c3','d4','e5','f6']      | Gives 6 - 1 = 5 elements                |
| x[1:6:2]  | Index 1 to 5 in steps of 2      | ['b2','d4','f6']                | Gives every other of 6 - 1 = 5 elements |
| x[5:]     | Index 5 to the end              | ['f6','g7','h8','i9','j10']     | Gives len(x)-5 = 5 elements             |
| x[:5]     | Index 0 to 5                    | ['a1','b2','c3','d4','e5']      | Gives 5 - 0 = 5 elements                |
| x[5:2:-1] | Index 5 to 3 (i.e., in reverse) | ['f6','e5','d4']                | Gives 5 - 2 = 3 elements                |
| x[::-1]   | Reverses the list               | ['j10','i9','h8',...,'b2','a1'] |                                         |

Do note that for `[i:j]`, slicing starts at `i` and ends at `j-1`

## 1.2 Arrays only | Subsetting by masking

In [3]:
import numpy as np
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
my_mask #return array with false for elements below 3 and true for others
np_array[my_mask] #returns elements that are true in mask array only

array([ 4,  5,  6,  7,  8,  9, 10])

In [ ]:
np_array[np_array > 3] #shortened 3 lines to 1

In [4]:
np_array[~(np_array > 3)] # '~' 'NOT' not operator

array([1, 2, 3])

In [5]:
np_array[(np_array > 3) & (np_array < 8)] #combining masks
np_array[(np_array < 3) | (np_array > 8)] 

array([4, 5, 6, 7])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [4]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [7]:
py_list_2d[3]
np_array_2d[3] #both return list at index 3, note array turned int into str

array(['4', 'D'], dtype='<U11')

In [9]:
py_list_2d[3][0]#index 0 of index 3 in the 2d array

4

In [10]:
np_array_2d[3, 0] #array has a different syntax for retrieving elements in multidimensional arrays.

'4'

In [11]:
py_list_2d[:3] #calls first 3 elements index 0-2
np_array_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]

In [9]:
py_list_2d[:3][0] #only [1,"A"] is returned, imagine [0] of the list containing py_list_2d elements 0-2


np_array_2d[:3, 0] #returns first element of sublists up to index 2
[x[0] for x in py_list_2d[:3]] #returns equivalent to line above using lists

[1, 2, 3]

In [14]:
py_list_2d[3:6][0] #returns first index of new list consisting of py_list_2d[3:6], therefore returning [4:'D']
np_array_2d[3:6,0] #returns first element from sublists of index 3-5
[x[0] for x in py_list_2d[3:6]] #returns equivalent to line above using lists

[4, 5, 6]

In [16]:
np_array_2d[:, 0] #returns all elements of all sublists
[x[0] for x in py_list_2d[:]] #returns equivalent to line above using lists


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

## 1.4 Growing lists

In [18]:
x=[1, 2]*5 #dups list [1,2] 5 times 
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [23]:
%%timeit
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
x

130 ns ± 0.278 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [25]:
%%timeit
x=[1]
x+= [2]
x+= [3]
x+= [4]
x

119 ns ± 0.409 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [26]:
%%timeit
x=[1]
x.append(2)
x.append(3)
x.append(4) #append appends element, ie argument data type inserted is new element
x 

69 ns ± 0.53 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [29]:
#%%timeit
x=[1]
x.extend([2])
x.extend([3])
x.extend([4]) #extend appends list, ie argument list contains data type of new element
x
#x.extend(5) #would throw an error as arg data type is not iterable

TypeError: 'int' object is not iterable

In [34]:
%%timeit
x = [1, 2, 3]
x += [4, 5, 6]
x

74.8 ns ± 0.705 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [35]:
%%timeit
x=[1, 2, 3]
x.extend([4, 5, 6])
x

76.3 ns ± 0.319 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [38]:
%%timeit
x=[1, 2, 3]
x.append([4, 5, 6])
x #slightly faster than the other 2 options, at ~60ns compared to ~75ns

61.2 ns ± 0.194 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


# Some loose ends

## 1.5 Tuples

In [39]:
a=(1, 2, 3)     # Define tuple
print(a[0])    # Access data

1


In [40]:
# The following will NOT work
a[0]=-1
a[0]+= [10]

TypeError: 'tuple' object does not support item assignment

## 1.6 Be VERY careful when copying

In [ ]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!
#explanation found in fundamentals_(nice)

In [42]:
x=[1, 2, 3]
y=x.copy()
z=x.copy() #correct way to not reference same list

## Footnotes